<?php
use Zend\Mvc\Application;
chdir(__DIR__.'/../../../..');
$loader = require 'vendor/autoload.php';

return Application::init(array(
	'modules'   => array(
        'ZfcBase',
        'ZfcUser',
    	'ZfcUserDoctrineORM',
    	'ZfJoacubUser',
    	'GoalioForgotPassword',
    	'GoalioForgotPasswordDoctrineORM',
    	'GoalioMailService',
    	'SlmLocale',
//     	'ZfJoacubAuthorize',
    	'ZfcUserAdmin',
//         'BjyModulus',
//         'BjyProfiler',
        'SlmLocale',
        'DelCountriesFlags',
        'AssetManager',
        'SxBootstrap',
//         'EdpSuperluminal',
        'Application',
//         'ScnSocialAuth',
//     	'ScnSocialAuthDoctrineORM',
//     	'OcraCachedViewResolver',
        'ZfcAdmin',
//         'CgmConfigAdmin',
        'SlmGoogleAnalytics',
        'DoctrineModule',
        'DoctrineORMModule',
//         'Heartsentwined\Cron',
//         'Heartsentwined\Geoname',
//         'PhlyContact',
//         'ZeSecurity',
        'CdliUserProfile',
        'MnsFormAnnotation',
//         'SearchEngineCrawler',
        'JoacubUploader',
        'FileBank',
//     	'Zf2Whoops',
        'WebinoImageThumb',
//     	'CustomediaGestionBase',
//         'CustomediaGestionCatalog',
//         'CustomediaGestionCustomers',
//         'CustomediaGestionSuppliers',
//         'CustomediaGestionBanks',
//         'CustomediaGestionSales',
//     	'CustomediaGestionWarehouseOrders',
//     	'ZfCustomediaCron',
//     	'ZfCustomediaInfo',
    	'StrokerForm',
        'JoacubBase',
//         'JoacubBlog',
        'DluTwBootstrap',
        'SuperMessenger',
        'JoacubCKEditor',
        'JoacubElFinder',
        'JoacubContentEditable',
//     	'ZfJoacubMinube',
    	
//     	'ZfJoacubCrawlers',
//     	'ZfJoacubMoviesList',
//     	'ZfjoacubMoviesThemeSocial',
//     	'GeboTheme',
//      	'Heartsentwined\Cron',
//      	'Heartsentwined\Geoname',
    	
    	
//     	'CheckAndGolf',
//     	'ZfApiMobileSql',
    	'AtAdmin',
    	'AtDataGrid',
//     	'GeonamesServer',
    	
    	
//     	'CustomediaWeb',
//     	'SxMail',
// 		'LaLineaDelHorizonte',
//     	'BjyModulus',
		'SynergyDataGrid',
//     	'ZfCharts',
//     	'CagStadistics',
    	'GeonamesServer',
    	'TranviaZgz',
//     	'TranviaZgzTheme',
    	'ZfChosen',
    	'JcNavigation',
    	'JcBlog'
	),
	'module_listener_options' => array(
		'config_glob_paths' => array(
			'config/autoload/{,*.}{global,local}.php',
		),
		'module_paths' => array(
			'vendor',
			'module'
		),
	),
));
