<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JcBlog\Module'                    => __DIR__ . '/Module.php',
    'JcBlog\Controller\PostController' => __DIR__ . '/src/JcBlog/Controller/PostController.php',
    'JcBlog\Entity\Post'               => __DIR__ . '/src/JcBlog/Entity/Post.php',
);
