<?php foreach ($this->posts as $post) : ?>
<div class="post post-<?=$post->id?>">
    <h2 class="entry-title">
        <a href="<?=$this->url('JcBlog-post', array('slug' => $post->slug))?>">
            <?=$this->escapeHtml($post->title)?>
        </a>
    </h2>
    <div class="entry-meta">
        <span class="entry-date">
            <?=strftime($this->config['date-format'], $post->created_at->getTimestamp())?>
        </span>
    </div>
    <div class="entry-content">
        <?=$this->escapeHtml($post->intro)?>
    </div>
</div>
<?php endforeach; ?>

<?=$this->paginationControl(
    $this->posts,
    'Elastic',
    'yogi-blog/pagination',
    ['route' => 'JcBlog']
)?>
